apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawler-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: crawler-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: crawler-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crawler-clusterrole
subjects:
  - kind: ServiceAccount
    name: crawler-serviceaccount
    namespace: default
